
name: buildmate
description: BuildMate - Construction Labour app (starter/demo)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  http: ^0.14.0
  shared_preferences: ^2.1.1
  razorpay_flutter: ^1.2.8 # placeholder for payments (Android/iOS)
  geolocator: ^9.0.2 # placeholder for location based matching

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
